### PR TITLE
Node-RED 1.0 adaption

### PR DESCRIPTION
**Pull request by hobbyquaker**
Hi! 

I created [a little script](https://github.com/rdmtc/midnight-red/blob/1.0-migration/css-changes.js) that replaced all CSS selectors with the new names used in Node-RED 1.0 (knolleary published [a table with the old and new selectors](https://github.com/rdmtc/midnight-red/blob/1.0-migration/css-changes.txt), that made that easy), also applied some manual fixes, not sure if I found everything, but on first sight it looks good. Would suggest you create a 1.0 branch and retarget this PR.

Regards,
Sebastian

### CODE REVIEW

**Comment by bonanitech** [comment]
Thanks for this PR.

I'm already working on an update for 1.0 based on [these instructions](https://twitter.com/knolleary/status/1131921077242933251). I will create a 1.0 branch later today and publish what I have so far.

I'm keeping this PR open for now.

**Comment by bonanitech** [comment]
1.0 branch created.

Please let me know what do you think of the code.

**Comment by hobbyquaker** [comment]
This includes massive redundancy (~80% of the style definitions just repeat what is already defined in the anyways loaded Node-RED style.min.css)
To be honest: I can't understand why you don't want to use the conversion I made, it results in 17kB of css, the one you created now is ~7.5 times (!) bigger: 126kB
Nevertheless: result looks same same on first sight, so it's up to you to decide ;-)

**Comment by bonanitech** [comment]
I'm aware of that. I am using the script (as suggested by knolleary) so that I can give feedback on it. When the final version is released, the CSS will have only what is needed.
And it's not that I don't want to use your conversion, I really appreciate your work. The point is that I do not intend to use my original CSS because I had to make some not-so-fine adjustments to make it work the way I wanted it to.

**Comment by bonanitech** [comment]
Closing this for the reason mentioned above.

Once again, thank you for your effort.

**Pull request closed without merging**
